module.exports = {
  tt0084787: {
    imdbID: "tt0084787",
    title: "The Thing",
    released: "1982-06-25",
    runtime: 109,
    genres: ["Horror", "Mystery", "Sci-Fi"],
    directors: ["John Carpenter"],
    writers: ["Bill Lancaster", "John W. Campbell Jr."],
    actors: ["Kurt Russell", "Wilford Brimley", "Keith David"],
    plot: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNGViZWZmM2EtNGYzZi00ZDAyLTk3ODMtNzIyZTBjN2Y1NmM1XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    metascore: 57,
    imdbRating: 8.2,
  },
  tt0120737: {
    imdbID: "tt0120737",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    released: "2001-12-19",
    runtime: 178,
    genres: ["Action", "Adventure", "Drama"],
    directors: ["Peter Jackson"],
    writers: ["J.R.R. Tolkien", "Fran Walsh", "Philippa Boyens"],
    actors: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"],
    plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
    metascore: 92,
    imdbRating: 8.8,
  },
  tt0085959: {
    imdbID: "tt0085959",
    title: "The Meaning of Life",
    released: "1983-03-31",
    runtime: 107,
    genres: ["Comedy", "Musical"],
    directors: ["Terry Jones", "Terry Gilliam"],
    writers: ["Graham Chapman", "John Cleese", "Terry Gilliam"],
    actors: ["John Cleese", "Terry Gilliam", "Eric Idle"],
    plot: "The comedy team takes a look at life in all of its stages in their own uniquely silly way.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZWJkNGY5MDAtYmVkMy00NzdiLTk5MzctMzA0MjMxMDY2NGYwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    metascore: 72,
    imdbRating: 7.5,
  },
  tt0107048: {
    imdbID: "tt0107048",
    title: "Groundhog Day",
    released: "1993-02-12",
    runtime: 101,
    genres: ["Comedy", "Drama", "Fantasy"],
    directors: ["Harold Ramis"],
    writers: ["Danny Rubin", "Harold Ramis"],
    actors: ["Bill Murray", "Andie MacDowell", "Chris Elliott"],
    plot: "A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day, and the day keeps repeating until he gets it right.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZWIxNzM5YzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
    metascore: 72,
    imdbRating: 8.1,
  },
  tt0124315: {
    imdbID: "tt0124315",
    title: "The Cider House Rules",
    released: "2000-01-07",
    runtime: 126,
    genres: ["Drama", "Romance"],
    directors: ["Lasse Hallström"],
    writers: ["John Irving"],
    actors: ["Tobey Maguire", "Charlize Theron", "Michael Caine"],
    plot: "A compassionate young man, raised in an orphanage and trained to be a doctor there, decides to leave to see the world.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNmY5YzA4OTQtOTQzZS00NDZmLTlhNzQtNzk5NTIyZWE2ZjVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    metascore: 75,
    imdbRating: 7.4,
  },
  tt0248808: {
    imdbID: "tt0248808",
    title: "For the Birds",
    released: "2001-11-02",
    runtime: 3,
    genres: ["Animation", "Short", "Comedy"],
    directors: ["Ralph Eggleston"],
    writers: ["Ralph Eggleston"],
    actors: ["Ralph Eggleston"],
    plot: "A group of snooty birds roosting on a telephone wire get their just deserts when a goofy bird drops in.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZjBhYzgyY2YtMTBhZS00NWIwLWIyYTgtMzhhYmFhZDNkMTQxXkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX300.jpg",
    metascore: 0.1,
    imdbRating: 8.0,
  }
};
